server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    #eviction-interval-timer-in-ms: 1000

    enableSelfPreservation: false
    #waitTimeInMsWhenSyncEmpty: 0
